import { LoadingContextProvider } from "@/context/loading";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <LoadingContextProvider>
            {children}
          </LoadingContextProvider>
      </body>
    </html>
  );
}
